# Generated by Django 2.0.13 on 2019-10-14 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nino', '0002_auto_20191014_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion_Medica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField(verbose_name='Edad del niño')),
                ('peso', models.IntegerField(verbose_name='Peso del niño')),
                ('desnutricion', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=3, verbose_name='Desnutrición')),
                ('altura', models.FloatField(verbose_name='Altura del niño')),
                ('circunferencia_brazo_derecho', models.FloatField(verbose_name='Circunferencia del brazo derecho')),
                ('circunferencia_brazo_izquierdo', models.FloatField(verbose_name='Circunferencia del brazo izquierdo')),
                ('circunferencia_abdominal', models.FloatField(verbose_name='Circunferencia abdominal')),
                ('imc', models.FloatField(verbose_name='I.M.C (Indice de masa corporal)')),
                ('antecendentes_medicos', models.TextField(verbose_name='Antecedentes médicos de importancia')),
                ('padece_alergias', models.CharField(blank=True, max_length=30, null=True, verbose_name='Padece de alegias, cual')),
                ('sintomas', models.TextField(blank=True, null=True, verbose_name='Sintomas')),
                ('impresion_clinica', models.TextField(verbose_name='Impresión clínica')),
                ('recomendacion', models.TextField(blank=True, null=True, verbose_name='Recomendaciones')),
                ('tratamiento', models.TextField(blank=True, null=True, verbose_name='Tratamiento')),
                ('proxima_cita', models.DateField(verbose_name='Próxima cita')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nino.NNA')),
            ],
            options={
                'verbose_name': 'Evaluacion_Medica',
                'verbose_name_plural': 'Evaluacion_Medicas',
            },
        ),
    ]
