# Generated by Django 2.0.13 on 2019-10-14 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area_Dental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(verbose_name='Dignóstico')),
                ('intervencion', models.TextField(verbose_name='Intervención médica')),
                ('proxima_cita', models.DateField(verbose_name='Próxima cita')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Area_Dental',
                'verbose_name_plural': 'Area_Dentals',
            },
        ),
        migrations.CreateModel(
            name='Area_Medica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.IntegerField(verbose_name='Peso del niño')),
                ('altura', models.FloatField(verbose_name='Altura del niño')),
                ('presencia_piojos', models.BooleanField(verbose_name='Presencia de piojos')),
                ('presencia_acaros', models.BooleanField(verbose_name='Presencia de acaros')),
                ('programa_vacunacion', models.BooleanField(verbose_name='Programa de vacunación')),
                ('examen_sangre', models.BooleanField(verbose_name='Examen de sangre')),
                ('examne_orina', models.BooleanField(verbose_name='Examen de orina')),
                ('estado_piel', models.TextField(verbose_name='Estado de la piel')),
            ],
            options={
                'verbose_name': 'Area_Medica',
                'verbose_name_plural': 'Area_Medicas',
            },
        ),
        migrations.CreateModel(
            name='Area_Psicologica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_emocional', models.TextField(null=True, verbose_name='Estado emocional')),
                ('aspecto_clinico', models.TextField(null=True, verbose_name='Aspecto clínico')),
                ('percepcion_situacion_desproteccion', models.BooleanField(verbose_name='Percepción de la situación de desprotección')),
                ('percepcion_calidad_vida', models.BooleanField(verbose_name='Percepción de la calidad de vida en su hogar')),
                ('percepcion_temores_actuales', models.TextField(null=True, verbose_name='Percepción de temores actuales')),
                ('percepcion_temores_futuros', models.TextField(null=True, verbose_name='Percepción de temores futuros')),
            ],
            options={
                'verbose_name': 'Area_Psicologica',
                'verbose_name_plural': 'Area_Psicologicas',
            },
        ),
        migrations.CreateModel(
            name='Area_Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_familiar', models.TextField(blank=True, null=True, verbose_name='Rol familiar')),
                ('visitas_autorizadas', models.BooleanField(verbose_name='Visitas Autorizadas')),
                ('recurso_familiar', models.CharField(blank=True, max_length=60, null=True, verbose_name='Recurso familiar')),
            ],
            options={
                'verbose_name': 'Area_Social',
                'verbose_name_plural': 'Area_Socials',
            },
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_enfermedad', models.CharField(max_length=60, verbose_name='Nombre de la enfermedad')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Enfermedad',
                'verbose_name_plural': 'Enfermedads',
            },
        ),
        migrations.CreateModel(
            name='Etnia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_etnia', models.CharField(max_length=60, verbose_name='Nombre de la etnia')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Etnia',
                'verbose_name_plural': 'Etnias',
            },
        ),
        migrations.CreateModel(
            name='Fuente_Estre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fuente', models.CharField(max_length=60, verbose_name='Fuente de estrés')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Fuente_Estre',
                'verbose_name_plural': 'Fuente_Estres',
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_idioma', models.CharField(max_length=60, verbose_name='Nombre del idioma')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
            },
        ),
        migrations.CreateModel(
            name='Motivo_Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_motivo', models.CharField(max_length=60, verbose_name='Motivo de ingreso')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Motivo_Ingreso',
                'verbose_name_plural': 'Motivo_Ingresos',
            },
        ),
        migrations.CreateModel(
            name='Nivel_Nutricion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=60, verbose_name='Nivel de nutrición')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Nivel_Nutricion',
                'verbose_name_plural': 'Nivel_Nutricions',
            },
        ),
        migrations.CreateModel(
            name='NNA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateField(verbose_name='Fecha de evaluación Biopsicosocial')),
                ('nombre_nino', models.CharField(max_length=60, verbose_name='Nombres del niño')),
                ('apellido_nino', models.CharField(max_length=60, verbose_name='Apellidos del niño')),
                ('image', models.ImageField(upload_to='img', verbose_name='Fotografía del niño')),
                ('cui', models.CharField(max_length=60, verbose_name='CUI')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=3, verbose_name='Sexo')),
                ('grado_educativo', models.CharField(blank=True, choices=[('P', 'Primario'), ('Pr', 'Pre-Primario'), ('Ba', 'Básico'), ('D', 'Diversificado')], max_length=30, null=True, verbose_name='Nivel educativo')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('lugar_nacimiento', models.CharField(max_length=60, verbose_name='Lugar de nacimiento')),
                ('lugar_residencia', models.CharField(max_length=60, verbose_name='Lugar de residencia')),
                ('ocupacion', models.CharField(blank=True, max_length=60, null=True, verbose_name='Ocupación')),
                ('religion', models.CharField(blank=True, max_length=30, null=True, verbose_name='Religión')),
                ('nombre_madre', models.CharField(max_length=100, verbose_name='Nombre completo de la madre')),
                ('nombre_padre', models.CharField(max_length=100, verbose_name='Nombre completo del padre')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso a CANICA')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('etnia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nino.Etnia')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nino.Idioma')),
                ('motivo_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nino.Motivo_Ingreso')),
            ],
            options={
                'verbose_name': 'Nino',
                'verbose_name_plural': 'Ninos',
            },
        ),
        migrations.CreateModel(
            name='Relacion_Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relacion', models.CharField(max_length=60, verbose_name='Tipo de relación familiar')),
            ],
            options={
                'verbose_name': 'Relacion_Familia',
                'verbose_name_plural': 'Relacion_Familias',
            },
        ),
        migrations.AddField(
            model_name='area_social',
            name='fuente_estres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nino.Fuente_Estre'),
        ),
        migrations.AddField(
            model_name='area_social',
            name='nino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nino.NNA'),
        ),
        migrations.AddField(
            model_name='area_social',
            name='relacion_familiar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nino.Relacion_Familia'),
        ),
        migrations.AddField(
            model_name='area_psicologica',
            name='enfermedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nino.Enfermedad'),
        ),
        migrations.AddField(
            model_name='area_psicologica',
            name='nino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nino.NNA'),
        ),
        migrations.AddField(
            model_name='area_medica',
            name='nino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nino.NNA'),
        ),
        migrations.AddField(
            model_name='area_medica',
            name='nivel_nutricion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nino.Nivel_Nutricion'),
        ),
        migrations.AddField(
            model_name='area_dental',
            name='nino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nino.NNA'),
        ),
    ]
