# Generated by Django 2.0.13 on 2019-10-14 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nna',
            options={'verbose_name': 'NNA', 'verbose_name_plural': 'NNAs'},
        ),
    ]
